# Playbook: deploy_ad.yml
# Purpose: Deploy a Windows Domain Controller
# Environment: OpenStack Windows VM with WinRM enabled
# Notes: Users and groups will be added later. Tasks are idempotent and will report OK.

- name: Deploy Windows Domain Controller
  hosts: domain_controller
  gather_facts: yes
  vars_files:
    - AD-var/setup-AD.yml   # updated path to vars file

  tasks:

    # Task 1: Install AD DS and DNS roles (idempotent)
    - name: 1. Ensure AD DS and DNS roles are installed
      win_feature:
        name:
          - AD-Domain-Services
          - DNS
        state: present
        include_sub_features: yes
        restart: yes
      register: ad_install

    # Task 2: Wait for server to restart after role installation
    - name: 2. Wait for server after AD DS installation
      wait_for_connection:
        delay: 10
        timeout: 600

    # Task 3: Promote to Domain Controller only if not already a DC
    - name: 3. Promote server to Domain Controller if needed
      win_shell: |
        Import-Module ADDSDeployment
        if (-not (Get-ADDomainController -ErrorAction SilentlyContinue)) {
          Install-ADDSForest `
            -DomainName "{{ domain_name }}" `
            -DomainNetbiosName "{{ netbios_name }}" `
            -SafeModeAdministratorPassword (ConvertTo-SecureString "{{ safe_mode_password }}" -AsPlainText -Force) `
            -Force
        }
      args:
        executable: powershell.exe
      register: dc_promotion
      changed_when: false
      ignore_errors: yes

    # Task 4: Wait for server to come back after DC promotion
    - name: 4. Wait for server after DC promotion
      wait_for_connection:
        delay: 10
        timeout: 600
