# Playbook: deploy_ad.yml
# Purpose: Deploy a Windows Domain Controller on an OpenStack VM
# Environment: Windows VM with WinRM already enabled
# Notes: Users and groups will be added in a later playbook.

- name: Deploy Windows Domain Controller
  hosts: domain_controller
  gather_facts: yes
  vars_files:
    - vars/ad.yml

  tasks:

    # Task 1: Install Active Directory Domain Services and DNS
    - name: 1. Install AD DS and DNS roles
      win_feature:
        name:
          - AD-Domain-Services
          - DNS
        state: present
        include_sub_features: yes
        restart: yes
      register: ad_install

    # Task 2: Wait for server to come back after role installation reboot
    - name: 2. Wait for server to restart after AD DS installation
      wait_for_connection:
        delay: 10
        timeout: 600
      when: ad_install.reboot_required

    # Task 3: Promote server to Domain Controller
    - name: 3. Promote server to Domain Controller
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{ netbios_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
        reboot: yes
      register: dc_promotion

    # Task 4: Wait for server to come back after DC promotion
    - name: 4. Wait for server to restart after DC promotion
      wait_for_connection:
        delay: 10
        timeout: 600
      when: dc_promotion.reboot_required
