# File: deploy-server.yml
#
# Purpose
# Configures a baseline Windows Server 2022 file server.
# Installs the File Server role, creates share directories on the system disk,
# publishes an SMB share, and applies NTFS permissions.
#
# Scope
# Standalone system
# Local permissions only
#
# Environment
# Windows Server 2022
# WinRM enabled
# Local Administrator credentials

- name: Baseline Windows 2022 File Server
  hosts: windows_fileserver
  gather_facts: yes
  vars_files:
    - vars/deploy.yml
  become: yes
  become_method: runas
  become_user: Administrator

  tasks:

    # Task 1: Install File Server role
    # Purpose: Enables SMB file sharing functionality
    - name: Install File Server role
      ansible.windows.win_feature:
        name: FS-FileServer
        state: present

    # Task 2: Create root directory for file shares
    # Purpose: Base directory to hold all file shares
    - name: Create root file share directory
      ansible.windows.win_file:
        path: "{{ file_share_root }}"
        state: directory

    # Task 3: Create Public share directory
    # Purpose: Directory to be exposed via SMB
    - name: Create Public folder
      ansible.windows.win_file:
        path: "{{ file_share_root }}\\{{ file_share_name }}"
        state: directory

    # Task 4: Create SMB share
    # Purpose: Publishes the Public directory over the network
    - name: Create SMB Public share
      ansible.windows.win_share:
        name: "{{ file_share_name }}"
        path: "{{ file_share_root }}\\{{ file_share_name }}"
        description: "{{ file_share_description }}"
        state: present

    # Task 5: Apply NTFS permissions
    # Purpose: Allows local Users group to modify files
    - name: Set NTFS permissions on Public share
      ansible.windows.win_acl:
        path: "{{ file_share_root }}\\{{ file_share_name }}"
        user: "{{ file_share_user }}"
        rights: "{{ file_share_permission }}"
        type: allow
        state: present
